//CODIGO CREADO DESDE 0 POR ANDRES-VPN
//wa.me//+573043603261

function style1(mensaje) {
  const textoEstilizado = mensaje.replace(/a/g, "𝚊")
    .replace(/b/g, "𝚋")
    .replace(/c/g, "𝚌")
    .replace(/d/g, "𝚍")
    .replace(/e/g, "𝚎")
    .replace(/f/g, "𝚏")
    .replace(/g/g, "𝚐")
    .replace(/h/g, "𝚑")
    .replace(/i/g, "𝚒")
    .replace(/j/g, "𝚓")
    .replace(/k/g, "𝚔")
    .replace(/l/g, "𝚕")
    .replace(/m/g, "𝚖")
    .replace(/n/g, "𝚗")
    .replace(/ñ/g, "ñ")
    .replace(/o/g, "𝚘")
    .replace(/p/g, "𝚙")
    .replace(/q/g, "𝚚")
    .replace(/r/g, "𝚛")
    .replace(/s/g, "𝚜")
    .replace(/t/g, "𝚝")
    .replace(/u/g, "𝚞")
    .replace(/v/g, "𝚟")
    .replace(/w/g, "𝚠")
    .replace(/x/g, "𝚡")
    .replace(/y/g, "𝚢")
    .replace(/z/g, "𝚣")
    //mayusculas
    .replace(/A/g, "𝙰")
    .replace(/B/g, "𝙱")
    .replace(/C/g, "𝙲")
    .replace(/D/g, "𝙳")
    .replace(/E/g, "𝙴")
    .replace(/F/g, "𝙵")
    .replace(/G/g, "𝙶")
    .replace(/H/g, "𝙷")
    .replace(/I/g, "𝙸")
    .replace(/J/g, "𝙹")
    .replace(/K/g, "𝙺")
    .replace(/L/g, "𝙻")
    .replace(/M/g, "𝙼")
    .replace(/N/g, "𝙽")
    .replace(/Ñ/g, "Ñ")
    .replace(/O/g, "𝙾")
    .replace(/P/g, "𝙿")
    .replace(/Q/g, "𝚀")
    .replace(/R/g, "𝚁")
    .replace(/S/g, "𝚂")
    .replace(/T/g, "𝚃")
    .replace(/U/g, "𝚄")
    .replace(/V/g, "𝚅")
    .replace(/W/g, "𝚆")
    .replace(/X/g, "𝚇")
    .replace(/Y/g, "𝚈")
    .replace(/Z/g, "𝚉")
    //numeros
    .replace(/0/g, "𝟶")
    .replace(/1/g, "𝟷")
    .replace(/2/g, "𝟸")
    .replace(/3/g, "𝟹")
    .replace(/4/g, "𝟺")
    .replace(/5/g, "𝟻")
    .replace(/6/g, "𝟼")
    .replace(/7/g, "𝟽")
    .replace(/8/g, "𝟾")
    .replace(/9/g, "𝟿")
    
    

return textoEstilizado
}

function style2(mensaje) {
  let textoEstilizado = mensaje
    .replace(/a/g, "ⓐ")
    .replace(/b/g, "ⓑ")
    .replace(/c/g, "ⓒ")
    .replace(/d/g, "ⓓ")
    .replace(/e/g, "ⓔ")
    .replace(/f/g, "ⓕ")
    .replace(/g/g, "ⓖ")
    .replace(/h/g, "ⓗ")
    .replace(/i/g, "ⓘ")
    .replace(/j/g, "ⓙ")
    .replace(/k/g, "ⓚ")
    .replace(/l/g, "ⓛ")
    .replace(/m/g, "ⓜ")
    .replace(/n/g, "ⓝ")
    .replace(/ñ/g, "ñ")
    .replace(/o/g, "ⓞ")
    .replace(/p/g, "ⓟ")
    .replace(/q/g, "ⓠ")
    .replace(/r/g, "ⓡ")
    .replace(/s/g, "ⓢ")
    .replace(/t/g, "ⓣ")
    .replace(/u/g, "ⓤ")
    .replace(/v/g, "ⓥ")
    .replace(/w/g, "ⓦ")
    .replace(/x/g, "ⓧ")
    .replace(/y/g, "ⓨ")
    .replace(/z/g, "ⓩ")
    //mayusculas
    .replace(/A/g, "Ⓐ")
    .replace(/B/g, "Ⓑ")
    .replace(/C/g, "Ⓒ")
    .replace(/D/g, "Ⓓ")
    .replace(/E/g, "Ⓔ")
    .replace(/F/g, "Ⓕ")
    .replace(/G/g, "Ⓖ")
    .replace(/H/g, "Ⓗ")
    .replace(/I/g, "Ⓘ")
    .replace(/J/g, "Ⓙ")
    .replace(/K/g, "Ⓚ")
    .replace(/L/g, "Ⓛ")
    .replace(/M/g, "Ⓜ")
    .replace(/N/g, "Ⓝ")
    .replace(/Ñ/g, "Ñ")
    .replace(/O/g, "Ⓞ")
    .replace(/P/g, "Ⓟ")
    .replace(/Q/g, "Ⓠ")
    .replace(/R/g, "Ⓡ")
    .replace(/S/g, "Ⓢ")
    .replace(/T/g, "Ⓣ")
    .replace(/U/g, "Ⓤ")
    .replace(/V/g, "Ⓥ")
    .replace(/W/g, "Ⓦ")
    .replace(/X/g, "Ⓧ")
    .replace(/Y/g, "Ⓨ")
    .replace(/Z/g, "Ⓩ")
    //numeros
    .replace(/0/g, "0")
    .replace(/1/g, "①")
    .replace(/2/g, "②")
    .replace(/3/g, "③")
    .replace(/4/g, "④")
    .replace(/5/g, "⑤")
    .replace(/6/g, "⑥")
    .replace(/7/g, "⑦")
    .replace(/8/g, "⑧")
    .replace(/9/g, "⑨")
    
    

return textoEstilizado
}

function style3(mensaje) {
  let textoEstilizado = mensaje
    .replace(/a/g, "𝐚")
    .replace(/b/g, "𝐛")
    .replace(/c/g, "𝐜")
    .replace(/d/g, "𝐝")
    .replace(/e/g, "𝐞")
    .replace(/f/g, "𝐟")
    .replace(/g/g, "𝐠")
    .replace(/h/g, "𝐡")
    .replace(/i/g, "𝐢")
    .replace(/j/g, "𝐣")
    .replace(/k/g, "𝐤")
    .replace(/l/g, "𝐥")
    .replace(/m/g, "𝐦")
    .replace(/n/g, "𝐧")
    .replace(/ñ/g, "ñ")
    .replace(/o/g, "𝐨")
    .replace(/p/g, "𝐩")
    .replace(/q/g, "𝐪")
    .replace(/r/g, "𝐫")
    .replace(/s/g, "𝐬")
    .replace(/t/g, "𝐭")
    .replace(/u/g, "𝐮")
    .replace(/v/g, "𝐯")
    .replace(/w/g, "𝐰")
    .replace(/x/g, "𝐱")
    .replace(/y/g, "𝐲")
    .replace(/z/g, "𝐳")
    //mayusculas
    .replace(/A/g, "𝐀")
    .replace(/B/g, "𝐁")
    .replace(/C/g, "𝐂")
    .replace(/D/g, "𝐃")
    .replace(/E/g, "𝐄")
    .replace(/F/g, "𝐅")
    .replace(/G/g, "𝐆")
    .replace(/H/g, "𝐇")
    .replace(/I/g, "𝐈")
    .replace(/J/g, "𝐉")
    .replace(/K/g, "𝐊")
    .replace(/L/g, "𝐋")
    .replace(/M/g, "𝐌")
    .replace(/N/g, "𝐍")
    .replace(/Ñ/g, "Ñ")
    .replace(/O/g, "𝐎")
    .replace(/P/g, "𝐏")
    .replace(/Q/g, "𝐐")
    .replace(/R/g, "𝐑")
    .replace(/S/g, "𝐒")
    .replace(/T/g, "𝐓")
    .replace(/U/g, "𝐔")
    .replace(/V/g, "𝐕")
    .replace(/W/g, "𝐖")
    .replace(/X/g, "𝐗")
    .replace(/Y/g, "𝐘")
    .replace(/Z/g, "𝐙")
    //numeros
    .replace(/0/g, "𝟎")
    .replace(/1/g, "𝟏")
    .replace(/2/g, "𝟐")
    .replace(/3/g, "𝟑")
    .replace(/4/g, "𝟒")
    .replace(/5/g, "𝟓")
    .replace(/6/g, "𝟔")
    .replace(/7/g, "𝟕")
    .replace(/8/g, "𝟖")
    .replace(/9/g, "𝟗")
    
    

return textoEstilizado
}

function style4(mensaje) {
  let textoEstilizado = mensaje
    .replace(/a/g, "🅐")
    .replace(/b/g, "🅑")
    .replace(/c/g, "🅒")
    .replace(/d/g, "🅓")
    .replace(/e/g, "🅔")
    .replace(/f/g, "🅕")
    .replace(/g/g, "🅖")
    .replace(/h/g, "🅗")
    .replace(/i/g, "🅘")
    .replace(/j/g, "🅙")
    .replace(/k/g, "🅚")
    .replace(/l/g, "🅛")
    .replace(/m/g, "🅜")
    .replace(/n/g, "🅝")
    .replace(/ñ/g, "ñ")
    .replace(/o/g, "🅞")
    .replace(/p/g, "🅟")
    .replace(/q/g, "🅠")
    .replace(/r/g, "🅡")
    .replace(/s/g, "🅢")
    .replace(/t/g, "🅣")
    .replace(/u/g, "🅤")
    .replace(/v/g, "🅥")
    .replace(/w/g, "🅦")
    .replace(/x/g, "🅧")
    .replace(/y/g, "🅨")
    .replace(/z/g, "🅩")
    //mayusculas
    .replace(/A/g, "🅐")
    .replace(/B/g, "🅑")
    .replace(/C/g, "🅒")
    .replace(/D/g, "🅓")
    .replace(/E/g, "🅔")
    .replace(/F/g, "🅕")
    .replace(/G/g, "🅖")
    .replace(/H/g, "🅗")
    .replace(/I/g, "🅘")
    .replace(/J/g, "🅙")
    .replace(/K/g, "🅚")
    .replace(/L/g, "🅛")
    .replace(/M/g, "🅜")
    .replace(/N/g, "🅝")
    .replace(/Ñ/g, "Ñ")
    .replace(/O/g, "🅞")
    .replace(/P/g, "🅟")
    .replace(/Q/g, "🅠")
    .replace(/R/g, "🅡")
    .replace(/S/g, "🅢")
    .replace(/T/g, "🅣")
    .replace(/U/g, "🅤")
    .replace(/V/g, "🅥")
    .replace(/W/g, "🅦")
    .replace(/X/g, "🅧")
    .replace(/Y/g, "🅨")
    .replace(/Z/g, "🅩")
    //numeros
    .replace(/0/g, "𝟎")
    .replace(/1/g, "𝟏")
    .replace(/2/g, "𝟐")
    .replace(/3/g, "𝟑")
    .replace(/4/g, "𝟒")
    .replace(/5/g, "𝟓")
    .replace(/6/g, "𝟔")
    .replace(/7/g, "𝟕")
    .replace(/8/g, "𝟖")
    .replace(/9/g, "𝟗")
    
    

return textoEstilizado
}

function style5(mensaje) {
  let textoEstilizado = mensaje
    .replace(/a/g, "𝖆")
    .replace(/b/g, "𝖇")
    .replace(/c/g, "𝖈")
    .replace(/d/g, "𝖉")
    .replace(/e/g, "𝖊")
    .replace(/f/g, "𝖋")
    .replace(/g/g, "𝖌")
    .replace(/h/g, "𝖍")
    .replace(/i/g, "𝖎")
    .replace(/j/g, "𝖏")
    .replace(/k/g, "𝖐")
    .replace(/l/g, "𝖑")
    .replace(/m/g, "𝖒")
    .replace(/n/g, "𝖓")
    .replace(/ñ/g, "ñ")
    .replace(/o/g, "𝖔")
    .replace(/p/g, "𝖕")
    .replace(/q/g, "𝖖")
    .replace(/r/g, "𝖗")
    .replace(/s/g, "𝖘")
    .replace(/t/g, "𝖙")
    .replace(/u/g, "𝖚")
    .replace(/v/g, "𝖛")
    .replace(/w/g, "𝖜")
    .replace(/x/g, "𝖝")
    .replace(/y/g, "𝖞")
    .replace(/z/g, "𝖟")
    //mayusculas
    .replace(/A/g, "𝕬")
    .replace(/B/g, "𝕭")
    .replace(/C/g, "𝕮")
    .replace(/D/g, "𝕯")
    .replace(/E/g, "𝕰")
    .replace(/F/g, "𝕱")
    .replace(/G/g, "𝕲")
    .replace(/H/g, "𝕳")
    .replace(/I/g, "𝕴")
    .replace(/J/g, "𝕵")
    .replace(/K/g, "𝕶")
    .replace(/L/g, "𝕷")
    .replace(/M/g, "𝕸")
    .replace(/N/g, "𝕹")
    .replace(/Ñ/g, "Ñ")
    .replace(/O/g, "𝕺")
    .replace(/P/g, "𝕻")
    .replace(/Q/g, "𝕼")
    .replace(/R/g, "𝕽")
    .replace(/S/g, "𝕾")
    .replace(/T/g, "𝕿")
    .replace(/U/g, "𝖀")
    .replace(/V/g, "𝖁")
    .replace(/W/g, "𝖂")
    .replace(/X/g, "𝖃")
    .replace(/Y/g, "𝖄")
    .replace(/Z/g, "𝖅")
    //numeros
    .replace(/0/g, "𝟎")
    .replace(/1/g, "𝟏")
    .replace(/2/g, "𝟐")
    .replace(/3/g, "𝟑")
    .replace(/4/g, "𝟒")
    .replace(/5/g, "𝟓")
    .replace(/6/g, "𝟔")
    .replace(/7/g, "𝟕")
    .replace(/8/g, "𝟖")
    .replace(/9/g, "𝟗")
    
    

return textoEstilizado
}


module.exports = {
   style1,
   style2,
   style3,
   style4,
   style5,
}